#!/bin/bash

set -e
set -f

readonly USERCONFIG="$HOME/.exitrc"

declare -A COMMANDS
DMENUV=dmenu
DMENU_FONT="-*-tamsyn-bold-*-*-*-20-*-*-*-*-*-*-*"
POSITION=-q

#######################################################################
# CONFIGURATION FILE
# * either ~/.exitrc or ./exitrc
# * populates COMMANDS[]
# * optionally sets DMENU_FONT
# * optionally sets POSITION
# * optionally sets DMENUV (dmenu with -m and -q patches)
#######################################################################

if [[ -r "$HOME/.exitrc" ]] ; then
  . "$USERCONFIG"
elif [[ -r "$PWD/exitrc" ]] ; then
  . "$PWD/exitrc"
fi

#######################################################################
# CLI - OVERRIDES USERCONFIG
#######################################################################

case "$1" in
  Top)        POSITION=                                 ;;
  TopQuarter) POSITION=-q                               ;;
  Middle)     POSITION=-m                               ;;
  Bottom)     POSITION=-b                               ;;
esac

#######################################################################

INPUT=$(for key in "${!COMMANDS[@]}" ; do
  echo "$key"
done | "$DMENUV" $POSITION -l "${#COMMANDS[@]}" -fn "$DMENU_FONT")

if [[ -n "${COMMANDS[$INPUT]}" ]] ; then
  ${COMMANDS[$INPUT]}
fi

exit $?
