#!/bin/bash

set -e
set -f

readonly DMENU_FONT="-*-tamsyn-bold-*-*-*-20-*-*-*-*-*-*-*"
declare -A COMMANDS
declare INPUT

COMMANDS[Lock]="xscreensaver-command -lock"
COMMANDS[Suspend]="gksudo xmessage foo"
COMMANDS[Hibernate]="gksudo xmessage hello"
COMMANDS[Log out]="pkill dwm"
COMMANDS[Reboot]="sudo rebot"
COMMANDS[Power off]="sudo pweroff"

INPUT=$(for key in "${!COMMANDS[@]}" ; do
  echo "$key"
done | ./dmenu-v/dmenu -m -l "${#COMMANDS[@]}" -fn "$DMENU_FONT")

if [[ -n "${COMMANDS[$INPUT]}" ]] ; then
  exec ${COMMANDS[$INPUT]}
fi

exit 0
