#!/bin/bash

# bunsen-exit-ng - a suckless session exit dialog for Bunsen Linux
# Copyright (C) 2015 Jens John <dev @ 2ion . de>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -f

readonly SCRIPT=${0##*/}
readonly SYSTEMCONFIG="/etc/exitrc"
USERCONFIG="$HOME/.exitrc"

declare -A COMMANDS
DMENUV=dmenuv
DMENU_FONT="-*-fixed-*-*-*-*-20-*-*-*-*-*-iso10646-*"
POSITION=tl
WIDTH=1.0

test_for_dmenuv () {
  [[ "$("$DMENUV" -v | cut -d, -f1)" =~ V$ ]] && return 0 || return 1
}

if [[ $1 = -h ]] ; then
  echo "Usage: ${0##*/} [-h] path-to-exitrc" >&2
  exit 0
fi

if [[ -r $1 ]] ; then
  USERCONFIG=$1
fi

#######################################################################
# CONFIGURATION FILE
# * either ~/.exitrc or ./exitrc
# * populates COMMANDS[]
# * optionally sets DMENU_FONT
# * optionally sets POSITION
# * optionally sets DMENUV (dmenu with -m and -q patches)
#######################################################################

if [[ -r "$USERCONFIG" ]] ; then
  . "$USERCONFIG"
elif [[ -r "$SYSTEMCONFIG" ]] ; then
  . "$SYSTEMCONFIG"
fi

POSITION="-g $POSITION"
WIDTH="-w $WIDTH"

#######################################################################

if ! test_for_dmenuv ; then
  echo "$SCRIPT: the binary pointed to by the DMENUV config option doesn't include the dmenu-v patchset" >&2
  echo "$SCRIPT: using fall-back options: ignoring gravity and width parameters"
  POSITION=
  WIDTH=
fi

INPUT=$(for key in "${!COMMANDS[@]}" ; do
  echo "$key"
done | sort | "$DMENUV" $POSITION $WIDTH -l "${#COMMANDS[@]}" -fn "$DMENU_FONT")

if [[ -n "${COMMANDS[$INPUT]}" ]] ; then
  ${COMMANDS[$INPUT]}
fi

exit $?
